[app]
GOOGLE_API_KEY = "AIzaSyB5owSrobFNLSyGGfBvQT9HBVWORNzQXM0"
MONGODB_URI = "mongodb+srv://fbarrueta:fbarrueta@cluster-fb.khq3ysh.mongodb.net/"
USER = "fbarrueta"
COHERE_API_KEY = "csVtsay6gHr9qrZHtGeFhqPrduHE80JKVWy1Zdbm"

[b2]
B2_BUCKET_NAME = "pc2-fb"
B2_READ_KEY_ID = "005b68b767762c90000000001"
B2_READ_APPLICATION_KEY = "read"
B2_WRITE_KEY_ID = "005b68b767762c90000000002"
B2_WRITE_APPLICATION_KEY = "write"
